#!/usr/bin/env python3
"""Regenerate docs/data.md from `rucio did list` output.

Reads the raw table from a file argument or stdin and writes a VitePress
markdown page that uses the <DidTable> Vue component for each
(campaign, data_name) group.

Usage
-----

  # From a file:
  python scripts/update_data_md.py rucio.txt

  # From stdin (the typical pipeline):
  docker run --rm eicweb/eic_xl:nightly \\
      rucio did list --filter 'is_background_mixed=true' 'epic:*' \\
    | python scripts/update_data_md.py

  # Custom output path:
  python scripts/update_data_md.py rucio.txt --out docs/data.md

By default writes to docs/data.md relative to the repo root (parent of
the directory containing this script).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

ENERGY_RE = re.compile(r"^\d+x\d+$")
MINQ2_RE = re.compile(r"minQ2=(\d+)")

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "docs" / "data.md"


def parse_did(did: str) -> dict | None:
    """Parse one Rucio DID. Returns None if it should be skipped."""
    if not did.startswith("epic:/"):
        return None
    parts = did[len("epic:/"):].split("/")
    if len(parts) < 5:
        return None
    partition, campaign, third, data_name, *rest = parts
    if partition not in ("FULL", "RECO"):
        return None
    if campaign == "main":
        # CI / branch / Test entries — not real campaigns
        return None
    if third != "epic_craterlake":
        return None
    energy = next((p for p in rest if ENERGY_RE.match(p)), None)
    if energy is None:
        return None
    # tail = everything after the partition (used to pair FULL+RECO twins)
    tail = "/".join([campaign, third, data_name, *rest])
    return {
        "did": did,
        "partition": partition,
        "campaign": campaign,
        "data_name": data_name,
        "energy": energy,
        "tail": tail,
        "rest": "/".join(rest),
    }


def read_dids(stream) -> tuple[list[dict], int]:
    """Pull DID strings out of the Rucio ASCII table and parse them.

    Returns (records, skipped_main_count).
    """
    records: list[dict] = []
    skipped_main = 0
    for line in stream:
        line = line.rstrip("\n")
        if not line.startswith("|"):
            continue
        first_col = line.split("|", 2)[1].strip()
        if not first_col.startswith("epic:/"):
            continue
        if "/main/" in first_col:
            skipped_main += 1
        rec = parse_did(first_col)
        if rec:
            records.append(rec)
    return records, skipped_main


def energy_key(e: str) -> tuple[int, int]:
    a, b = e.split("x")
    return int(a), int(b)


def row_sort_key(row: dict) -> tuple:
    """Sort rows inside one data-name table: energy, then minQ2, then DID."""
    a, b = energy_key(row["energy"])
    m = MINQ2_RE.search(row["did"])
    minq2 = int(m.group(1)) if m else 10**9
    # FULL before RECO at the same (energy, minQ2)
    kind_order = 0 if row["kind"] == "FULL" else 1
    return (a, b, minq2, kind_order, row["did"])


def render(records: list[dict], skipped_main: int) -> str:
    # Group: campaign -> data_name -> list of {did, kind, energy}
    groups: dict[str, dict[str, list[dict]]] = defaultdict(lambda: defaultdict(list))
    for r in records:
        groups[r["campaign"]][r["data_name"]].append({
            "did": r["did"],
            "kind": r["partition"],
            "energy": r["energy"],
        })

    out: list[str] = []
    out += [
        "# Data",
        "",
        "Available **background-mixed** datasets in Rucio. Source of truth:",
        "",
        "```bash",
        "rucio did list --filter 'is_background_mixed=true' 'epic:*'",
        "```",
        "",
        "This page is regenerated by the `update-data-md` skill — see",
        "[`.claude/skills/update-data-md/SKILL.md`](https://github.com/eic/ai-epic-background/blob/main/.claude/skills/update-data-md/SKILL.md)",
        "for the procedure, and `scripts/update_data_md.py` for the parser.",
        "",
        f"_Last updated: **{date.today().isoformat()}**_",
        "",
        "## Conventions",
        "",
        "- **FULL** — DD4hep simulation output (sim-level, full Geant4 hits).",
        "- **RECO** — EICrecon reconstruction output (reco-level).",
        "- Each table covers one `(campaign, data_name)` pair. Rows are sorted",
        "  by beam energy, then by `minQ2`, with the **FULL** row above its",
        "  **RECO** twin.",
        "- `main/` branch / CI / Test entries are filtered out — only versioned",
        f"  campaigns are shown ({skipped_main} `main/` entries skipped on the",
        "  last run).",
        "- `epic_craterlake` is the only detector configuration; the full DID",
        "  including that segment is shown in each row.",
        "- Use the per-row 📋 to copy a single DID, or the top-of-table button",
        "  to copy all DIDs in a dataset (newline-separated, ready to paste",
        "  into `rucio download`, a shell loop, or a config file).",
        "",
    ]

    for campaign in sorted(groups, reverse=True):
        out += [f"## Campaign {campaign}", ""]
        for data_name in sorted(groups[campaign]):
            rows = sorted(groups[campaign][data_name], key=row_sort_key)
            out += [f"### {data_name}", ""]
            # JSON.dumps with double quotes -> attribute uses single quotes
            payload = json.dumps(rows, separators=(",", ":"))
            out += [f"<DidTable :rows='{payload}' />", ""]

    out += [
        "## Using these DIDs",
        "",
        "A DID is just a pointer — it resolves to a set of files (PFNs) on Rucio",
        "Storage Elements. Two upstream pages cover this in full; this section is",
        "the bare minimum to get you started.",
        "",
        "- 📚 [Rucio usage tutorial](https://eic.github.io/tutorial-file-access/02-rucio_usage/index.html) — setup, auth, full command reference.",
        "- 📚 [Use-cases tutorial](https://eic.github.io/tutorial-file-access/03-use_cases/index.html) — download vs. stream, batch workflows, common patterns.",
        "",
        "### 1. One-time setup (inside `eic-shell`)",
        "",
        "```bash",
        "# Voms / OIDC auth — pick what matches your account (see Rucio tutorial).",
        "rucio whoami",
        "```",
        "",
        "If `rucio whoami` returns your identity, you're done. If not, follow the",
        "auth steps on the [Rucio usage tutorial](https://eic.github.io/tutorial-file-access/02-rucio_usage/index.html).",
        "",
        "### 2. See what's inside a dataset",
        "",
        "```bash",
        "rucio did list-content 'epic:/RECO/26.04.1/epic_craterlake/Bkg_Exact1S_2us/GoldCt/10um/DIS/NC/10x100/minQ2=1'",
        "```",
        "",
        "### 3. Download files locally",
        "",
        "```bash",
        "rucio download 'epic:/RECO/26.04.1/epic_craterlake/Bkg_Exact1S_2us/GoldCt/10um/DIS/NC/10x100/minQ2=1'",
        "```",
        "",
        "Downloads land in a directory tree mirroring the DID. Add `--nrandom N`",
        "to pull only a sample, or `--rse <RSE>` to pin a storage element.",
        "",
        "### 4. Stream over XRootD (no local copy)",
        "",
        "Most analyses can read directly from XRootD — faster on the JLab farm and",
        "saves disk:",
        "",
        "```bash",
        "# List replica URLs for a DID",
        "rucio list-file-replicas --pfns 'epic:/RECO/26.04.1/.../minQ2=1' | head",
        "",
        "# Then open them directly, e.g. in ROOT / uproot / EICrecon:",
        "root -l 'root://dtn-eic.jlab.org//volatile/eic/EPIC/RECO/.../file.edm4eic.root'",
        "```",
        "",
        "See [use-cases](https://eic.github.io/tutorial-file-access/03-use_cases/index.html) for the recommended patterns when running many jobs over a dataset.",
        "",
    ]

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "input",
        nargs="?",
        type=Path,
        help="Path to the raw `rucio did list` output. If omitted, read from stdin.",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Output markdown file (default: {DEFAULT_OUT.relative_to(REPO_ROOT)})",
    )
    args = ap.parse_args()

    if args.input is None:
        stream = sys.stdin
    else:
        stream = args.input.open("r", encoding="utf-8")

    try:
        records, skipped_main = read_dids(stream)
    finally:
        if args.input is not None:
            stream.close()

    if not records:
        print("error: no valid DIDs parsed from input — is the input a Rucio `did list` table?", file=sys.stderr)
        return 1

    text = render(records, skipped_main)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")

    n_campaigns = len({r["campaign"] for r in records})
    n_data_names = len({(r["campaign"], r["data_name"]) for r in records})
    print(
        f"Parsed {len(records)} valid DIDs (skipped {skipped_main} `main/` entries)\n"
        f"Rendered {n_campaigns} campaign(s), {n_data_names} data-name table(s)\n"
        f"Wrote {args.out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
