#!/usr/bin/env python3
"""Refresh the generated tables in docs/data.md from `rucio did list` output.

Reads the raw table from a file argument or stdin and rewrites ONLY the
machine-managed parts of docs/data.md:

  * the `<DidTable>` blocks, between the
    `<!-- BEGIN TABLES ... -->` and `<!-- END TABLES -->` markers, and
  * the `_Last updated: **YYYY-MM-DD**_` line.

Everything else on the page — the intro, conventions, and the "Using
these DIDs" tutorial — is plain hand-editable markdown that this script
never touches. The prose lives in the page, not in this file.

Usage
-----

  # From a file:
  python scripts/update_data_md.py rucio.txt

  # From stdin (the typical pipeline):
  docker run --rm eicweb/eic_xl:nightly \\
      rucio did list --filter 'is_background_mixed=true' 'epic:*' \\
    | python scripts/update_data_md.py

  # Custom output path:
  python scripts/update_data_md.py rucio.txt --out docs/data.md

By default updates docs/data.md relative to the repo root (parent of
the directory containing this script). The target file must already exist
and contain the BEGIN/END TABLES markers.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

ENERGY_RE = re.compile(r"^\d+x\d+$")
MINQ2_RE = re.compile(r"minQ2=(\d+)")

BEGIN_MARKER = "<!-- BEGIN TABLES (generated by scripts/update_data_md.py — do not edit by hand) -->"
END_MARKER = "<!-- END TABLES -->"
# Match the whole BEGIN..END block (markers included) so we can swap it out.
TABLES_BLOCK_RE = re.compile(
    re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
    re.DOTALL,
)
# The single dynamic line in the prose: `_Last updated: **YYYY-MM-DD**_`.
DATE_LINE_RE = re.compile(r"^_Last updated: \*\*.*?\*\*_$", re.MULTILINE)

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "docs" / "data.md"


def parse_did(did: str) -> dict | None:
    """Parse one Rucio DID. Returns None if it should be skipped."""
    if not did.startswith("epic:/"):
        return None
    parts = did[len("epic:/"):].split("/")
    if len(parts) < 5:
        return None
    partition, campaign, third, data_name, *rest = parts
    if partition not in ("FULL", "RECO"):
        return None
    if campaign == "main":
        # CI / branch / Test entries — not real campaigns
        return None
    if third != "epic_craterlake":
        return None
    energy = next((p for p in rest if ENERGY_RE.match(p)), None)
    if energy is None:
        return None
    # tail = everything after the partition (used to pair FULL+RECO twins)
    tail = "/".join([campaign, third, data_name, *rest])
    return {
        "did": did,
        "partition": partition,
        "campaign": campaign,
        "data_name": data_name,
        "energy": energy,
        "tail": tail,
        "rest": "/".join(rest),
    }


def read_dids(stream) -> tuple[list[dict], int]:
    """Pull DID strings out of the Rucio ASCII table and parse them.

    Returns (records, skipped_main_count).
    """
    records: list[dict] = []
    skipped_main = 0
    for line in stream:
        line = line.rstrip("\n")
        if not line.startswith("|"):
            continue
        first_col = line.split("|", 2)[1].strip()
        if not first_col.startswith("epic:/"):
            continue
        if "/main/" in first_col:
            skipped_main += 1
        rec = parse_did(first_col)
        if rec:
            records.append(rec)
    return records, skipped_main


def energy_key(e: str) -> tuple[int, int]:
    a, b = e.split("x")
    return int(a), int(b)


def row_sort_key(row: dict) -> tuple:
    """Sort rows inside one data-name table: energy, then minQ2, then DID."""
    a, b = energy_key(row["energy"])
    m = MINQ2_RE.search(row["did"])
    minq2 = int(m.group(1)) if m else 10**9
    # FULL before RECO at the same (energy, minQ2)
    kind_order = 0 if row["kind"] == "FULL" else 1
    return (a, b, minq2, kind_order, row["did"])


def render_tables(records: list[dict]) -> str:
    """Render just the marker-delimited tables block (markers included).

    This is the only generated content. All surrounding prose lives in
    docs/data.md as hand-editable markdown.
    """
    # Group: campaign -> data_name -> list of {did, kind, energy}
    groups: dict[str, dict[str, list[dict]]] = defaultdict(lambda: defaultdict(list))
    for r in records:
        groups[r["campaign"]][r["data_name"]].append({
            "did": r["did"],
            "kind": r["partition"],
            "energy": r["energy"],
        })

    out: list[str] = [BEGIN_MARKER, ""]
    for campaign in sorted(groups, reverse=True):
        out += [f"## Campaign {campaign}", ""]
        for data_name in sorted(groups[campaign]):
            rows = sorted(groups[campaign][data_name], key=row_sort_key)
            out += [f"### {data_name}", ""]
            # JSON.dumps with double quotes -> attribute uses single quotes
            payload = json.dumps(rows, separators=(",", ":"))
            out += [f"<DidTable :rows='{payload}' />", ""]
    out += [END_MARKER]
    return "\n".join(out)


def splice(page: str, records: list[dict]) -> str:
    """Replace the generated tables block and the date line in `page`.

    Raises ValueError if the BEGIN/END markers aren't found, so we never
    silently clobber a page that's missing them.
    """
    if not TABLES_BLOCK_RE.search(page):
        raise ValueError(
            f"could not find the tables markers ({BEGIN_MARKER!r} ... "
            f"{END_MARKER!r}) in the page — refusing to overwrite"
        )
    page = TABLES_BLOCK_RE.sub(lambda _m: render_tables(records), page)
    page = DATE_LINE_RE.sub(
        f"_Last updated: **{date.today().isoformat()}**_", page, count=1
    )
    return page


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "input",
        nargs="?",
        type=Path,
        help="Path to the raw `rucio did list` output. If omitted, read from stdin.",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Output markdown file (default: {DEFAULT_OUT.relative_to(REPO_ROOT)})",
    )
    args = ap.parse_args()

    if args.input is None:
        stream = sys.stdin
    else:
        stream = args.input.open("r", encoding="utf-8")

    try:
        records, skipped_main = read_dids(stream)
    finally:
        if args.input is not None:
            stream.close()

    if not records:
        print("error: no valid DIDs parsed from input — is the input a Rucio `did list` table?", file=sys.stderr)
        return 1

    if not args.out.exists():
        print(
            f"error: {args.out} does not exist. This script only refreshes the\n"
            f"generated tables inside an existing page; it does not create the\n"
            f"page or its prose. Restore docs/data.md (with the BEGIN/END TABLES\n"
            f"markers) from git first.",
            file=sys.stderr,
        )
        return 1

    page = args.out.read_text(encoding="utf-8")
    try:
        text = splice(page, records)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    args.out.write_text(text, encoding="utf-8")

    n_campaigns = len({r["campaign"] for r in records})
    n_data_names = len({(r["campaign"], r["data_name"]) for r in records})
    print(
        f"Parsed {len(records)} valid DIDs (skipped {skipped_main} `main/` entries)\n"
        f"Rendered {n_campaigns} campaign(s), {n_data_names} data-name table(s)\n"
        f"Wrote {args.out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
